#!/usr/bin/env bash

# set -v
# set -x

nonascii() {
  #LANG=C
  grep --color=auto --line-number -H '[^ -~]\+';
}

git diff --cached --name-only | while read FILE; do

  # if [[ "$FILE" =~ ^.+(md)$ ]]; then
  if [[ "$FILE" =~ ^(^.+(xml|md)$) ]]
  then

    changed=`git diff --cached $FILE | grep --line-number '[^ -~]\+'`

    if [[ -z "$changed" ]]
    then
      exit 0
    fi

    if [ $? == 0 ]
    then
      echo -e "\nWARNING: Found non-ascii values. Please fix them before committing.\n"
      echo "$FILE"
      echo "---"
      echo "$changed"
      echo "---"
      exit 1
    fi

  fi
done
