#!/usr/bin/env bash

command -v perl >/dev/null 2>&1 || {
  echo >&2 "I require 'perl' but it's not installed.  Skipping .."; exit 0;
}

git diff --cached --name-only | while read FILE; do
  if [[ "$FILE" =~ ^.+(pl|cfg)$ ]]; then
      if [[ -f $FILE ]]; then
          perl -c "$FILE" 1> /dev/null
          if [ $? -ne 0 ]; then
              echo -e "\n\nWARNING: Aborting commit due to files with syntax errors. Fix them before committing.\n\n" >&2
              exit 1
          fi
      fi
  fi
done || exit $?
