#!/bin/sh
#
# This will abort "git commit" if trailing whitespaces were found
# in the files to be committed.
#
# Taken with courtesy from:
# https://gist.github.com/mxgrn/663933/2c6944702cb4974cae4e91d40fc066b5b58fe467
#
# Modified to only abort and not replace inline.
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

if test "$(git diff-index --check --cached $against --)"
then
  echo "[ERROR] Aborting .."
  git diff-index --check --cached $against
  exit 1
fi
