#!/usr/bin/env bash

HOOKS="\
pre-commit-trailing-whitespaces \
pre-commit-crlf-to-lf \
pre-commit-perl \
pre-commit-non-ascii \
pre-commit-valid-xml \
pre-commit-merge-conflicts"

for hook in $HOOKS
do
    echo "Running hook: $hook"
    # run hook if it exists
    # if it returns with nonzero exit with 1 and thus abort the commit
    if [ -f "$(dirname -- $0)/$hook" ]; then
        "$(dirname -- $0)/$hook"
        if [ $? != 0 ]; then
           exit 1
        fi
    else
        echo "Error: file $hook not found."
        echo "Aborting commit. Make sure the hook is in $SCRIPTPATH and executable."
        echo "You can disable it by removing it from the list in $SCRIPT."
        echo "You can skip all pre-commit hooks with --no-verify (not recommended)."
        exit 1
    fi
done
